dist: trusty
os: 
  - linux-ppc64le
sudo: required
language: go
go:
- "1.12.1"

script:
  - cd $GOPATH/src/github.com
  - mkdir Masterminds
  - cd Masterminds
  - git clone https://github.com/Masterminds/glide.git
  - cd glide
  - ls
  - make build
  - ls
  - sudo chmod 777 glide
  - ./glide
