dist: bionic
os: linux
arch: ppc64le
sudo: required
language: go
go:
- "1.13.x"

script:
  - cd $GOPATH/src/github.com
  - mkdir Masterminds
  - cd Masterminds
  - git clone https://github.com/Masterminds/glide.git
  - cd glide
  - make build
  - sudo chmod 777 glide
  - ./glide
